name: site test
on:
  pull_request:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install mkdocs-material plantuml-markdown
      - name: test site
        run: mkdocs build
